#!/usr/bin/env python
# -*- coding: utf-8 -*-

# t2jrbot - simple but elegant IRC bot
# Copyright © 2014 Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import ConfigParser
import hashlib

import t2jrbot

def parse_args():
    parser = argparse.ArgumentParser(description="Simple but elegant IRC bot")
    parser.add_argument("config_file", metavar="CONFIG_FILE",
                        help="configuration file")
    return parser.parse_args()

def parse_conf(filepath):
    bot_conf = {}
    plugins_conf = {}

    config_parser = ConfigParser.RawConfigParser()
    config_parser.read(filepath)

    for section in config_parser.sections():
        if section == "bot":
            bot_conf.update(dict(config_parser.items(section)))
            continue

        if section.startswith("plugins."):
            plugin_name = section.lstrip("plugins.")
            plugin_conf = plugins_conf.setdefault(plugin_name, {})
            plugin_conf.update(dict(config_parser.items(section)))
            continue

    return bot_conf, plugins_conf

def main():
    options = parse_args()

    bot_conf, plugins_conf = parse_conf(options.config_file)

    server = bot_conf.get("server", "localhost")
    port = int(bot_conf.get("port", 6667))
    nick = bot_conf.get("nick", "t2jrbot")
    plugin_dirs = bot_conf.get("plugin_dirs", "").splitlines()
    plugins = bot_conf.get("plugins", "").splitlines()

    bot = t2jrbot.Bot(server, port, nick)

    for plugin_dir in plugin_dirs:
        bot.add_plugin_dir(plugin_dir)

    for plugin_name in plugins:
        bot.load_plugin(plugin_name, plugins_conf.get(plugin_name, {}))

    bot.run()

if __name__ == "__main__":
    main()
