#!/usr/bin/env python
# -*- coding: utf-8 -*-

# t2jrbot - simple but elegant IRC bot
# Copyright © 2014 Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import hashlib

import t2jrbot

def command_admin_list(bot, nick, host, channel, this_command, argstr):
    admins = ["%s!%s" % (nick, host) for nick, host in bot.admins]
    bot.send_irc_privmsg(channel, "%s: %s" % (nick, " ".join(admins)))

def command_admin_add(bot, nick, host, channel, this_command, argstr):
    admin_nick, admin_host = parse_admin_arg(argstr)
    bot.add_admin(admin_nick, admin_host)

def command_admin_remove(bot, nick, host, channel, this_command, argstr):
    admin_nick, admin_host = parse_admin_arg(argstr)
    bot.remove_admin(admin_nick, admin_host)

def command_help(bot, nick, host, channel, this_command, argstr):
    command = argstr.strip()
    if not command:
        commands = sorted(bot.command_descriptions.keys())
        bot.send_irc_privmsg(channel,
                             "%s: Commands: %s"
                             % (nick, ", ".join(commands)))
        bot.send_irc_privmsg(channel,
                             "%s: To get detailed help on a command, "
                             "use %s COMMAND, e.g. %s %s"
                             % (nick, this_command, this_command, this_command))
    else:
        try:
            descr = bot.command_descriptions[command]
        except KeyError:
            bot.send_irc_privmsg(channel,
                                 "%s: command '%s' not found" % (nick, command))
        else:
            bot.send_irc_privmsg(channel, "%s: %s - %s"
                                 % (nick, command, descr))

def command_quit(bot, nick, host, channel, this_command, argstr):
    bot.quit(argstr)

def irc_ping(bot, prefix, this_irccmd, params):
    bot.send_irc_pong(bot.nick)

def irc_error(bot, prefix, this_irccmd, params):
    sys.exit(1)

def irc_001(bot, prefix, this_irccmd, params):
    # Update the nick after successful connection because
    # the server might have truncated or otherwise modified
    # the nick we requested.
    bot.nick = params[0]
    bot.send_irc_join(options.channel)

def irc_privmsg(bot, prefix, this_irccmd, params):
    nick, sep, host = prefix.partition("!")

    target, text = params

    if target == bot.nick:
        # User-private messages are not supported and are silently
        # ignored.
        return

    channel = target

    # Ignore all leading whitespaces.
    text = text.lstrip()

    if not text.startswith("%s:" % bot.nick):
        # The message is not designated to me, ignore.
        return

    # Strip my nick from the beginning of the text.
    commandstr = text[len("%s:" % bot.nick):].lstrip()

    command, _, argstr = commandstr.partition(' ')

    bot.eval_command(nick, host, channel, command, argstr)

def parse_admin_arg(admin):
    admin_nick, sep, admin_host = admin.partition("!")
    admin_nick = admin_nick.strip()
    admin_host = admin_host.strip()
    if not admin_nick or not sep or not admin_host:
        raise argparse.ArgumentTypeError("malformed admin identifier, should "
                                         "be of form 'nick!user@example.org'")
    return admin_nick, admin_host

def parse_args():
    parser = argparse.ArgumentParser(description="Simple but elegant IRC bot")
    parser.add_argument("-p", "--port", type=int, default=6667,
                        help="port of the server which bot connects to, default=6667")
    parser.add_argument("server", metavar="SERVER",
                        help="address of the server which bot connects to")
    parser.add_argument("channel", metavar="CHANNEL",
                        help="channel which bot joins after a connection is established")
    parser.add_argument("-n", "--nick", default=None,
                        help="nickname of the bot")
    parser.add_argument("-a", "--admin", action="append", dest="admins", default=[],
                        type=parse_admin_arg, metavar="ADMIN",
                        help="admin of the bot (e.g. 'nick!user@example.org'), "
                        "can be given multiple times to add multiple admins")
    parser.add_argument("-L", "--plugin-dir", action="append", dest="plugin_dirs",
                        default=[], metavar="PLUGIN_DIR",
                        help="add plugin directory, can be given multiple times "
                        "to add multiple directories")
    parser.add_argument("-l", "--load-plugin", action="append", dest="plugin_names",
                        default=[], metavar="PLUGIN",
                        help="load plugin, can be given multiple times to "
                        "load multiple plugins")
    return parser.parse_args()

options = None

def main():
    global options
    options = parse_args()

    if options.nick is None:
        md5 = hashlib.md5()
        md5.update(options.server)
        md5.update(options.channel)
        options.nick = "t2jrbot_%s" % md5.hexdigest()

    bot = t2jrbot.Bot(options.server, options.port, options.nick)

    # Built-in bot commands.
    bot.register_command("!admin_list", command_admin_list,
                         "List bot admins. Usage: !admin_list",
                         require_admin=False)
    bot.register_command("!admin_add", command_admin_add,
                         "Add a bot admin. Usage: !admin_add NICK!USER@HOST, "
                         "e.g. !admin_add fanatic!fan.atic@example.org")
    bot.register_command("!admin_remove", command_admin_remove,
                         "Remove a bot admin. Usage: !admin_remove NICK!USER@HOST, "
                         "e.g. !admin_remove fanatic!fan.atic@example.org")
    bot.register_command("!help", command_help,
                         "Since you got this far, "
                         "you already know what this command does.",
                         require_admin=False)
    bot.register_command("!quit", command_quit, "Quits the bot, "
                         "optionally with a message. "
                         "Usage: !quit [MESSAGE], "
                         "e.g. !quit So Long, and Thanks for All the Fish!")

    bot.add_irc_callback(irc_ping, irccmd="PING")
    bot.add_irc_callback(irc_error, irccmd="ERROR")
    bot.add_irc_callback(irc_001, irccmd="001")
    bot.add_irc_callback(irc_privmsg, irccmd="PRIVMSG")

    for admin_nick, admin_host in options.admins:
        bot.add_admin(admin_nick, admin_host)

    for plugin_dir in options.plugin_dirs:
        bot.add_plugin_dir(plugin_dir)

    for plugin_name in set(options.plugin_names):
        bot.load_plugin(plugin_name)

    bot.run()

if __name__ == "__main__":
    main()
