#!/usr/bin/env python
# -*- coding: utf-8 -*-

# tjjrbot - simple but elegant IRC bot
# Copyright © 2014 Tuomas Räsänen <tuomasjjrasanen@tjjr.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse

import tjjrbot

def command_help(bot, nick, host, channel, command, argstr):
    bot.send_ircmsg_privmsg(channel, "%s: List of commands:" % nick)
    for cmd, descr in bot.command_descriptions.items():
        bot.send_ircmsg_privmsg(channel, "%s: %s - %s" % (nick, cmd, descr))

def command_say(bot, nick, host, channel, command, argstr):
    bot.send_ircmsg_privmsg(channel, argstr)
    bot.send_ircmsg_privmsg(channel, "-- %s" % nick)

def parse_args():
    parser = argparse.ArgumentParser(description="Simple but elegant IRC bot")
    parser.add_argument("-p", "--port", type=int, default=6667,
                        help="port of the server which bot connects to, default=6667")
    parser.add_argument("server", metavar="SERVER",
                        help="address of the server which bot connects to")
    parser.add_argument("channel", metavar="CHANNEL",
                        help="channel which bot joins after a connection is established")
    parser.add_argument("-n", "--nick", default="tjjrbot",
                        help="nickname of the bot, default='tjjrbot'")
    return parser.parse_args()

def main():
    options = parse_args()
    bot = tjjrbot.Bot(options.server, options.port, options.nick, options.channel)
    bot.register_command("!help", command_help, "show help", require_admin=False)
    bot.register_command("!say", command_say, "say something to the channel")
    bot.run()

if __name__ == "__main__":
    main()
